sharedDir: '.config'
outputDir: 'lib'

mergeRules:
  '.gitignore': true
  '.npmignore': true

ignorePatterns:
  '.gitignore':
    [
      '*.log',
      '*.pid',
      '*.pid.lock',
      '*.seed',
      '*.tgz',
      '.env',
      '.yarn-integrity',
      '/.eslintcache',
      '/.eslintignore',
      '/.eslintrc',
      '/.husky/',
      '/src/**/__generated__',
      '/tsconfig.json',
      'coverage',
      'lib',
      'logs',
      'node_modules/',
      'pids',
      'tsconfig.tsbuildinfo',
      'yarn-debug.log*',
      'yarn-error.log*',
    ]
  '.npmignore':
    [
      '**/__mocks__/**',
      '**/__tests__/**',
      '.changelogrc.yml',
      '.config',
      '.env',
      '.eslintignore',
      '.eslintrc',
      '.ghinfo',
      '.gitattributes',
      '.github',
      '.husky',
      'CODE_OF_CONDUCT.md',
      'codecov.yml',
      'codegen.yml',
      'coverage/',
      'docs/',
      'example/',
      'lib/scripts/',
      'media/',
      'node_modules/',
      'src/',
      'tsconfig.json',
      'typings/',
    ]
  '.eslintignore': ['__generated__', 'lib', '*.svg']
  '.prettierignore': ['lib/', '/src/**/__generated__']

executableFiles: ['.husky/commit-msg', '.husky/pre-commit']

scripts:
  'build': 'npm-run-all build:generate build:ts'
  'build:ts': 'rimraf lib && tsc --extendedDiagnostics'
  'build:generate': 'rimraf src/components/__generated__ && node --loader ts-node/esm ./src/scripts/build.ts'
  'generate': 'npm-run-all generate:*'
  'generate:changelog': 'changelog generate --bump'
  'generate:ghinfo': 'ghinfo generate -d media -t utils'
  'lint': 'npm-run-all lint:*'
  'lint:eslint': 'eslint "src/**" --ext .ts'
  'prepare': 'npm-run-all prepare:*'
  'prepare:config': 'icons-shared-config'
  'prepare:husky': 'husky install'
  'release': 'npm-run-all prepare build lint generate'

dependencies:
  - '@tagproject/docs-shared-config': '1.x'
  - '@tagproject/vscode-shared-config': '2.X'
  - "@types/react": '18.x'
  - '@typescript-eslint/eslint-plugin': '5.x'
  - '@typescript-eslint/parser': '5.x'
  - 'changelog-guru'
  - 'eslint': '8.x'
  - 'eslint-config-prettier': '8.x'
  - 'eslint-plugin-import': '2.x'
  - 'eslint-plugin-jest': '27.x'
  - 'eslint-plugin-node': '11.x'
  - 'eslint-plugin-optimize-regex': '1.x'
  - 'eslint-plugin-promise': '6.x'
  - 'eslint-plugin-react': '7.x'
  - 'eslint-plugin-react-hooks': '4.x'
  - 'ghinfo'
  - 'husky': '8.x'
  - 'rimraf'
  - 'ts-node': '10.x'
  - 'typescript': '4.x'



package:
  manager: 'npm'
  type: 'module'
  peerDependencies:
    'react': '18.x'
    'react-dom': '18.x'
