sharedDir: '.config'
outputDir: 'lib'

mergeRules:
  '.gitignore': true
  '.npmignore': true

ignorePatterns:
  '.gitignore':
    [
      '*.log',
      '*.pid',
      '*.pid.lock',
      '*.seed',
      '*.tgz',
      '.env',
      '.yarn-integrity',
      '/.eslintcache',
      '/.eslintignore',
      '/.eslintrc',
      '/.figma.yml',
      '/.husky/',
      '/src/**/__generated__',
      '/src/icons',
      '/tsconfig.json',
      'coverage',
      'lib',
      'logs',
      'node_modules/',
      'pids',
      'tsconfig.tsbuildinfo',
      'yarn-debug.log*',
      'yarn-error.log*',
    ]
  '.npmignore':
    [
      '**/__mocks__/**',
      '**/__tests__/**',
      '.changelogrc.yml',
      '.config',
      '.env',
      '.eslintignore',
      '.eslintrc',
      '.figma.yml',
      '.ghinfo',
      '.gitattributes',
      '.github',
      '.husky',
      'CODE_OF_CONDUCT.md',
      'codecov.yml',
      'codegen.yml',
      'coverage/',
      'docs/',
      'example/',
      'lib/scripts/',
      'media/',
      'node_modules/',
      'src/',
      'tsconfig.json',
      'typings/',
    ]
  '.eslintignore': ['__generated__', 'lib', '*.svg']
  '.prettierignore': ['lib/', '/src/**/__generated__']

executableFiles: ['.husky/commit-msg', '.husky/pre-commit']

scripts:
  'build': 'npm-run-all build:prepare build:extract build:generate build:ts'
  'build:ts': 'rimraf lib && tsc --extendedDiagnostics'
  'build:extract': 'node --experimental-specifier-resolution=node node_modules/.bin/figma-portal extract -d src/icons -p GitHub -f sophty -c .figma.icons.yml'
  'build:generate': 'node --experimental-specifier-resolution=node --loader ts-node/esm ./src/scripts/build.ts'
  'build:prepare': 'rimraf src/icons src/components/__generated__'
  'generate': 'npm-run-all generate:*'
  'generate:changelog': 'node --experimental-specifier-resolution=node node_modules/.bin/changelog generate --bump'
  'generate:ghinfo': 'node --experimental-specifier-resolution=node node_modules/.bin/ghinfo generate -d media -t utils'
  'generate:media': 'node --experimental-specifier-resolution=node node_modules/.bin/figma-portal extract -d media -f sophty -p GitHub'
  'lint': 'npm-run-all lint:*'
  'lint:eslint': 'eslint "src/**" --ext .ts'
  'prepare': 'npm-run-all prepare:*'
  'prepare:config': 'node --experimental-specifier-resolution=node node_modules/.bin/icons-shared-config'
  'prepare:husky': 'husky install'
  'release': 'npm-run-all prepare build lint generate'

dependencies:
  - '@tagproject/docs-shared-config': '1.x'
  - '@tagproject/vscode-shared-config': '1.X'
  - '@typescript-eslint/eslint-plugin': '5.x'
  - 'changelog-guru'
  - 'eslint': '8.x'
  - 'eslint-config-prettier': '8.x'
  - 'eslint-plugin-import': '2.x'
  - 'eslint-plugin-jest': '26.x'
  - 'eslint-plugin-node': '11.x'
  - 'eslint-plugin-optimize-regex': '1.x'
  - 'eslint-plugin-promise': '6.x'
  - 'eslint-plugin-react': '7.x'
  - 'eslint-plugin-react-hooks': '4.x'
  - 'figma-portal'
  - 'ghinfo': '3.x'
  - 'husky': '7.x'
  - 'npm-run-all'
  - 'rimraf'
  - 'ts-node': '10.x'
  - 'typescript': '4.x'

package:
  manager: 'npm'
  type: 'module'
