sharedDir: '.config'
outputDir: 'lib'

mergeRules:
  '.gitignore': true
  '.npmignore': true

ignorePatterns:
  '.gitignore':
    [
      '*.log',
      '*.pid',
      '*.pid.lock',
      '*.seed',
      '*.tgz',
      '.env',
      '.yarn-integrity',
      '/.eslintcache',
      '/.eslintignore',
      '/.eslintrc',
      '/.husky/',
      '/src/**/__generated__',
      '/tsconfig.json',
      '/tsconfig.lib.json',
      'coverage',
      'lib',
      'logs',
      'node_modules/',
      'pids',
      'tsconfig.tsbuildinfo',
      'yarn-debug.log*',
      'yarn-error.log*',
    ]
  '.npmignore':
    [
      '**/__mocks__/**',
      '**/__tests__/**',
      '.changelogrc.yml',
      '.config',
      '.env',
      '.eslintignore',
      '.eslintrc',
      '.ghinfo',
      '.gitattributes',
      '.github',
      '.husky',
      'CODE_OF_CONDUCT.md',
      'codecov.yml',
      'codegen.yml',
      'coverage/',
      'docs/',
      'example/',
      'lib/scripts/',
      'media/',
      'node_modules/',
      'src/',
      'tsconfig.json',
      'tsconfig.lib.json',
      'typings/',
    ]
  '.eslintignore': ['__generated__', 'lib', '*.svg']
  '.prettierignore': ['lib/', '/src/**/__generated__']

executableFiles: ['.husky/commit-msg', '.husky/pre-commit']

scripts:
  'build': 'run-s build:generate build:ts'
  'build:ts': 'rimraf lib && tsc -p tsconfig.lib.json --extendedDiagnostics && copyfiles -f src/assets/**/* lib/assets'
  'build:generate': 'rimraf src/components/__generated__ && node --loader ts-node/esm ./src/scripts/build.ts'
  'generate': 'run-s generate:*'
  'generate:changelog': 'changelog generate --bump'
  'generate:ghinfo': 'ghinfo generate -d media -t utils'
  'lint': 'run-s lint:*'
  'lint:eslint': 'eslint src --ext=.tsx,.ts'
  'prepare': 'run-s prepare:*'
  'prepare:config': 'icons-shared-config'
  'prepare:husky': 'husky install'
  'release': 'run-s prepare build lint generate'

package:
  manager: 'npm'
  type: 'module'
  types: './lib/index.d.ts'
  exports:
    ".": "./lib/index.js"
    "./theme.css": "./lib/assets/theme.css"
  peerDependencies:
    'clsx': '2.x'
    'react': '18.x'
    'react-dom': '18.x'
